# Generated by Django 5.1 on 2024-08-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_backend', '0005_alter_transaction_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
    ]
